blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/ZacharyPatten/Towel/discussions/new
    about: Ask and answer questions.
  - name: Show and Tell
    url: https://github.com/ZacharyPatten/Towel/discussions/new
    about: Show off your projects that use Towel.
