name: Towel Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Sources/Towel/**'
      - 'Tools/docfx_project/**'
jobs:
  docfx:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nikeee/docfx-action@v1.0.0
      name: docfx
      with:
        args: Tools/docfx_project/docfx.json
    - name: coverage
      run: |
        dir /s /b coverage.cobertura.xml > COVERAGEPATH.xml
        set /p COVERAGEPATH < COVERAGEPATH.xml
        move %COVERAGEPATH% coverage.cobertura.xml
        dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.8.11
        reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:Tools/docfx_project/_site/coveragereport" -reporttypes:Html
        move coverage.cobertura.xml Tools/docfx_project/_site/coveragereport/coverage.cobertura.xml
    - uses: maxheld83/ghpages@master
      name: gh-pages publish
      env:
        BUILD_DIR: Tools/docfx_project/_site
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
