name: Towel Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Sources/Towel/**'
      - 'Tools/docfx_project/**'
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301
    - name: dotnet test
      run: dotnet test --collect:"XPlat Code Coverage"
    - name: find coverage.cobertura.xml path
      run: find . -print | grep -i 'coverage.cobertura.xml' > COVERAGEPATH.txt
    - name: move coverage.cobertura.xml file
      run: |
        COVERAGEPATH=$(<COVERAGEPATH.txt)
        mv $COVERAGEPATH coverage.cobertura.xml
    - name: dotnet tool install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.8.11
    - uses: nikeee/docfx-action@v1.0.0
      name: docfx
      with:
        args: Tools/docfx_project/docfx.json
    - name: chmod
      run: sudo chmod -R 777 Tools/docfx_project/_site
    - name: make coverage report directory
      run: mkdir Tools/docfx_project/_site/coveragereport
    - name: generate coverage report
      run: reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:Tools/docfx_project/_site/coveragereport" -reporttypes:Html
    - name: extract coverage ratio
      run: cat coverage.cobertura.xml | head -2 > coverage.xml
    - name: tail coverage xml
      run: echo "</coverage>" >> coverage.xml
    - name: move coverage.xml
      run: mv coverage.xml Tools/docfx_project/_site/coveragereport/coverage.xml
    - uses: maxheld83/ghpages@master
      name: gh-pages publish
      env:
        BUILD_DIR: Tools/docfx_project/_site
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
